version: '3'
services:
  simplemeca:
    image: sean0921/simplemeca
    build:
      context: '.'
      dockerfile: Dockerfile
    environment:
      - PORT="5000"
      - NUM_WORKER="4"
    ports:
      - "5000:5000"
