# fly.toml file generated for simplemeca-flask on 2022-08-26T13:20:37+08:00

app = "simplemeca-flask"
kill_signal = "SIGTERM"
kill_timeout = 300
processes = []

[env]
  PORT = "5000"
  NUM_WORKER = "1"
  ALWAYS_TLS = "True"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
